# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VN9Y0R4UA9U5vK_Fj1y8PIxx1EV4ex1d
"""

import streamlit as st
import geopandas as gpd
import pandas as pd
import folium
from streamlit_folium import st_folium

st.set_page_config(page_title="Crop Monitoring Dashboard", layout="wide")

st.title("🌾 Plot Wise Crop Monitoring Dashboard")

# ---------------- LOAD DATA ---------------- #
@st.cache_data
def load_plots():
    gdf = gpd.read_file(r"F:\ndviApp\Rabi_plot.shp")
    gdf.columns = gdf.columns.str.lower()
    return gdf

plots = load_plots()

# ---------------- LOAD NDVI CSV ---------------- #
@st.cache_data
def load_ndvi():
    df = pd.read_csv(r"F:\ndviApp\ndvi.csv")
    df.columns = df.columns.str.lower()   # ensures plot_id, 2020, 2021...
    return df

ndvi_df = load_ndvi()

# ---------------- SIDEBAR ---------------- #
st.sidebar.header("🔍 Select Year")
selected_year = st.sidebar.selectbox(
    "Select Year", ["2020", "2021", "2022", "2023", "2024"]
)

# ---------------- NDVI FUNCTION ---------------- #
def get_ndvi(pid, year):
    row = ndvi_df[ndvi_df["plot_id"] == pid]

    if not row.empty and year in row.columns:
        return float(row.iloc[0][year])

    return None

# ---------------- COLOR FUNCTION ---------------- #
def get_color(ndvi):
    if ndvi is None:
        return "gray"
    elif ndvi < 0.2:
        return "red"
    elif ndvi < 0.4:
        return "orange"
    else:
        return "green"

# ---------------- MAP ---------------- #
st.subheader("📍 Click on Plot")

plots_map = plots.to_crs(epsg=4326)
center = plots_map.geometry.centroid.iloc[0]

m = folium.Map(location=[center.y, center.x], zoom_start=15, tiles=None)

# Satellite background
folium.TileLayer(
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attr="Esri",
    name="Satellite",
    overlay=False,
    control=True
).add_to(m)

# ---------------- ADD POLYGONS ---------------- #
for _, row in plots_map.iterrows():

    geom = row.geometry
    pid = int(row['id'])  # ensure type match
    crop_type = row['crop_type']

    # Get NDVI
    ndvi_val = get_ndvi(pid, selected_year)

    # Health classification
    if ndvi_val is None:
        health = "No Data"
    elif ndvi_val < 0.2:
        health = "Poor"
    elif ndvi_val < 0.4:
        health = "Moderate"
    else:
        health = "Healthy"

    color = get_color(ndvi_val)

    popup_text = f"""
    <b>Plot ID:</b> {pid}<br>
    <b>Crop:</b> {crop_type}<br>
    <b>Year:</b> {selected_year}<br>
    <b>NDVI:</b> {round(ndvi_val,3) if ndvi_val is not None else 'No Data'}<br>
    <b>Health:</b> {health}
    """

    folium.GeoJson(
        geom,
        style_function=lambda x, color=color: {
            "fillColor": color,
            "color": color,
            "weight": 2,
            "fillOpacity": 0.5
        },
        popup=folium.Popup(popup_text, max_width=250)
    ).add_to(m)

# Layer control
folium.LayerControl().add_to(m)

# Show map
st_folium(m, width=1000, height=600)